version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9900:9900"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3901:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge